### ISSUE TITLE
Some canvases aren't being given an ID after importing into access, causing the editor to fail to load

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#455] opened 2022-01-15 14:40 UTC
Update: temp fix pushed

Maybe the canvases are issued noids over time so we might need to handle when id isn't set?

I'm going to mark id as optional (temporarily if this is unexpected behaviour) so that the editor still loads.

If this is expected then that will be the fix in general!

See bl.test1 image 646 etc.

**Comment by RussellMcOrmond** [comment] 2022-01-15 17:06
This is a bug in Smelter, and I will look into it next week.  No idea how that can happen and not be flagged by the import.

I looked up http://iris.tor.c7a.ca:5984/_utils/index.html#database/dipstaging/oocihm.lac_reel_c6455 and this is a recent Smelt on Friday, so not something that was fixed yet.

**Comment by RussellMcOrmond** [comment] 2022-01-15 17:37
There are two runs of Hammer2 that demonstrate this bug.  I don't know if there are any access documents that haven't been made public that have this problem.


https://admin.canadiana.ca/couchview/access/metadatabus/hammerStatus?endkey=%5Bfalse%5D&inclusive=true&keytype=json&range=true&reduce=false&startkey=%5Bfalse%5D

**Comment by RussellMcOrmond** [comment] 2022-01-17 12:55
My guess is that this was caused by an interesting race condition.

* A canvas is created by Smelter
* [CopyCanvasImage ](https://github.com/crkn-rcdr/CIHM-Meta/tree/main/lib/CIHM/Meta/CopyCanvasImage)finds the canvas and marks it as orphaned (as the manifest hasn't been written yet)
* I manually run [canvas-orphan](https://github.com/crkn-rcdr/Systems-Administration/blob/main/data-tools/bin/canvas-orphan)  which deleted orphaned canvases
* Smelter would look for the ID in a quick lookup, and no longer find it -- this wasn't a condition I considered, so it would leave the ID field blank.


I've added additional checks in Smelter to try to detect a missing ID.

This isn't a problem that will happen in the future, as CopyCanvasImage is a transition tool that will be decommissioned once the data has been copied.  https://github.com/orgs/crkn-rcdr/projects/3

@brittnylapierre can close this once she is comfortable with the solution.

**Closed** 2022-01-17 17:00 UTC
Labels: bug
