### ISSUE TITLE
DMD - back-end file processing

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/Access-Platform#421] opened 2021-12-16 22:18 UTC
User Story: 
As a Metadata Analyst I need to be able to upload and process metadata files quickly so that I can add or update metadata without constantly having to task switch.

**Comment by RussellMcOrmond** [comment] 2022-01-14 14:56
Note: If you use GET and PUT for attachments, there is no need to use b64 at all.  The use of b64 only adds additional compute and memory overhead unnecessarily (both for your app, as well as CouchDB).

https://docs.couchdb.org/en/stable/api/document/attachments.html

**Comment by RussellMcOrmond** [comment] 2022-03-30 13:24
This is related to  #260 and #328 , and those may actually be a duplicate of this one.

**Closed** 2022-04-13 19:59 UTC
Labels: service-admin, important enhancement
